saida = [{'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'Nintendo started out as a playing card manufacturer.', 'correct_answer': 'True',
          'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'Super Mario Bros. was released in 1990.', 'correct_answer': 'False',
          'incorrect_answers': ['True']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In &quot;Overwatch,&quot; an allied McCree will say &quot;Step right up&quot; upon using his ultimate ability Deadeye.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.',
          'correct_answer': 'False', 'incorrect_answers': ['True']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'Pistons were added to Minecraft in Beta 1.5.', 'correct_answer': 'False',
          'incorrect_answers': ['True']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'Mortal Kombat was almost based on Jean-Claude Van Damme movie.', 'correct_answer': 'True',
          'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In Monster Hunter Generations, guild style is a type of hunting style.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'David Baszucki was a co-founder of ROBLOX Corporation.', 'correct_answer': 'True',
          'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after the lead singer of the band &quot;Nine Inch Nails&quot;.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.',
          'correct_answer': 'False', 'incorrect_answers': ['True']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In &quot;Call Of Duty: Zombies&quot;, you can upgrade the &quot;Apothicon Servant&quot; in the &quot;Shadows Of Evil&quot; map.',
          'correct_answer': 'False', 'incorrect_answers': ['True']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In the Season One Championship of &quot;League of Legends&quot;, the highest achievable rank was Diamond.',
          'correct_answer': 'False', 'incorrect_answers': ['True']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'Shang Tsung is a playable character in Mortal Kombat XL.', 'correct_answer': 'False',
          'incorrect_answers': ['True']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.',
          'correct_answer': 'True', 'incorrect_answers': ['False']},
         {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'medium',
          'question': 'In the Resident Evil series, Leon S. Kennedy is a member of STARS.', 'correct_answer': 'False',
          'incorrect_answers': ['True']}]
[['Nintendo started out as a playing card manufacturer.', 'True'], [
    'DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.',
    'True'], ['Super Mario Bros. was released in 1990.', 'False'], [
     'In &quot;Overwatch,&quot; an allied McCree will say &quot;Step right up&quot; upon using his ultimate ability Deadeye.',
     'True'],
 ['In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.',
  'False'],
 ['TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.', 'True'],
 ['Pistons were added to Minecraft in Beta 1.5.', 'False'],
 ['Mortal Kombat was almost based on Jean-Claude Van Damme movie.', 'True'],
 ['In Monster Hunter Generations, guild style is a type of hunting style.', 'True'],
 ['David Baszucki was a co-founder of ROBLOX Corporation.', 'True'], [
     'In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after the lead singer of the band &quot;Nine Inch Nails&quot;.',
     'True'], [
     'In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.',
     'False'], [
     'In &quot;Call Of Duty: Zombies&quot;, you can upgrade the &quot;Apothicon Servant&quot; in the &quot;Shadows Of Evil&quot; map.',
     'False'], [
     'The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.',
     'True'],
 ['In the Season One Championship of &quot;League of Legends&quot;, the highest achievable rank was Diamond.', 'False'],
 ['During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.', 'True'], [
     'In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.',
     'True'], ['Shang Tsung is a playable character in Mortal Kombat XL.', 'False'],
 ['The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.', 'True'],
 ['In the Resident Evil series, Leon S. Kennedy is a member of STARS.', 'False']]
